#!/usr/bin/env python3

import requests
import sys
import urllib3

# Desabilitar avisos de requisições não verificadas
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def check_website(url):
    try:
        # Definindo um tempo limite de 5 segundos para a requisição
        response = requests.get(url, timeout=5, verify=False)
        if response.status_code == 200:
            print(f"{response.status_code}")
        else:
            print(f"{response.status_code}")
    except requests.exceptions.Timeout:
        print("0")  # codigo de erro para down
    except requests.exceptions.ConnectionError:
        print("0")  #codigo de erro para down
    except requests.exceptions.RequestException as e:
        print(f"RequestException: {e}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./check_website.py <url>")
    else:
